import os
from building import *

Import('osconfig')

cwd = GetCurrentDir()
group = []
list = os.listdir(cwd)

if osconfig.ARCH in list:
    group = group + SConscript(os.path.join(osconfig.ARCH, 'SConscript'))

Return('group')