from building import *
import os

Import('osconfig')

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp') + Glob('*.S')
CPPPATH = [cwd,os.path.join(cwd,"..","include")]
ASFLAGS = ''

group = DefineGroup('src', src, depend = [''], CPPPATH = CPPPATH, ASFLAGS = ASFLAGS)

list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
